name: ulusoyapps_flutter
description: An application for showcasing several flutter implementations.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 1.1.0
  shared_preferences: 0.5.12
  provider: 4.3.2+2
  material_design_icons_flutter: 4.0.5655
  fl_chart: 0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/

