name: ulusoyapps_flutter
description: An application for showcasing several flutter implementations.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  google_fonts: ^2.1.0
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  material_design_icons_flutter: ^4.0.5955
  fl_chart: ^0.36.1
  url_strategy: ^0.2.0
  scrollable_positioned_list: 0.1.10
  tuple: ^2.0.0
  flutter_lorem: ^2.0.0
  equatable: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/

