name: multi_page_scrollable_bottom_sheet
description: A demo app to demonstrate mulyi page scrollable bottomsheet.

version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  very_good_analysis: ^2.4.0
  google_fonts: ^2.2.0
  material_design_icons_flutter: ^5.0.6595
  flutter_lorem: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/

